[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
amm_basein = "D4i1459Wu1XTM12BDLHHYuR7uDmA62G1iAZJCsJTs4PD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.test.ts"
